import { AfterViewInit, Component, ViewChild } from '@angular/core';
import { MatPaginator } from '@angular/material/paginator';
import { MatSort } from '@angular/material/sort';
import { MatTableDataSource } from '@angular/material/table';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { DummydataService } from '../services/dummydata.service';
export interface UserData {
  name: string;
  type: boolean;
  companies: any;
  date: any;
}

@Component({
  selector: 'app-custom-table',
  templateUrl: './custom-table.component.html',
  styleUrls: ['./custom-table.component.css'],
})
// I usually approch to make a custom table, But I was checking out with the material one as world is moving out with material designs.
// The size may not match the original website but I tried to amke it in same proportion. 
// The apis arent made and thus a custom autogenerated json is stored in the dummydataservice.
export class CustomTableComponent implements AfterViewInit {
  selectedRowIndex = -1;
  displayedColumns: string[] = [
    'date',
    'name',
    'No of Entities',
    'actions',
    'details',
  ];
  detailsList = [];

  dataSource: MatTableDataSource<UserData>;

  @ViewChild(MatPaginator) paginator: MatPaginator;
  @ViewChild(MatSort) sort: MatSort;
  constructor(
    private dataservice: DummydataService,
    private modalService: NgbModal
  ) {
    this.dataSource = new MatTableDataSource(this.dataservice.data);
  }

  ngAfterViewInit(): void {
    this.dataSource.paginator = this.paginator;
    this.dataSource.sort = this.sort;
  }

  applyFilter(event: Event) {
    const filterValue = (event.target as HTMLInputElement).value;
    this.dataSource.filter = filterValue.trim().toLowerCase();

    if (this.dataSource.paginator) {
      this.dataSource.paginator.firstPage();
    }
  }

  highlight(row) {
    // we generally used index based system , but in the autogenerated json we missed to add a index field and thus using a name based indexing.
    this.selectedRowIndex = row.name;
    this.detailsList = row?.companies || [];
  }

  NotAvailabe(customContent) {
    this.modalService.open(customContent, {
      windowClass: 'dark-modal',
      backdrop: 'static',
      size: 'lg',
    });
  }
}
